### ISSUE TITLE
Version 1.0.0 Stable Release Discussion

### ISSUE THREAD

**Issue by mvdmakesthings** [DBSInteractive/DBS-Share-Count#7]
We need to have a plan for what all we want in this plugin and get a "todo" and milestone goals setup to plan for a full 1.0.0 stable release for this. Any thoughts or ideas on what we should do/add? Maybe the addition of other social platforms?

**Comment by dbswebsite** [comment]
Are we still doing the WP plugin thing? I think that could be something
simple like a shortcode based implementation for the editor, and a template
function.

On Tue, Oct 20, 2015 at 11:44 AM, Michael Large notifications@github.com
wrote:

> We need to have a plan for what all we want in this plugin and get a
> "todo" and milestone goals setup to plan for a full 1.0.0 stable release
> for this. Any thoughts or ideas on what we should do/add? Maybe the
> addition of other social platforms?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DBSInteractive/DBS-Share-Count/issues/7.

## 

Hal Burgiss
CTO and DevOps
_DBS__>Interactive_ http://www.dbswebsite.com/

## 

NOTICE: This E-mail (including attachments) is covered by the Electronic Communications 
Privacy Act, 18 U.S.C. 2510-2521, is confidential and may be legally 
privileged. If you are not the intended recipient, you are hereby notified 
that any retention, dissemination, distribution or copying of this communication 
is prohibited. Please reply to the sender that you have received the 
message in error, then delete it.

**Comment by mvdmakesthings** [comment]
I agree. :+1: Let's definitely set that as a goal for v1.
